# .coderabbit.yaml
language: go

# Define custom rules for Go code
rules:
  - name: Ensure error handling is present
    description: Checks that functions return errors and handle them correctly.
    severity: error
    match: |
      function .* {
        if (!return_type.contains("error")) {
          raise "Functions should return an error type if they can fail."
        }
      }

  - name: Enforce idiomatic Go naming conventions
    description: Variables and functions should follow Go naming conventions.
    severity: warning
    match: |
      identifier .* {
        if (identifier != identifier.lower() and !is_exported) {
          raise "Private identifiers should be in camelCase."
        }
      }

  - name: Avoid global variables
    description: Discourage the use of global variables as they can lead to side effects and reduce code clarity.
    severity: warning
    match: |
      variable .* {
        if (is_global) {
          raise "Avoid using global variables where possible."
        }
      }

  - name: Check for unused imports
    description: Ensures there are no unused imports.
    severity: warning
    match: |
      import .* {
        if (is_unused) {
          raise "Remove unused imports to keep the code clean."
        }
      }

  - name: Enforce comments on exported functions
    description: All exported functions should have comments following Go's docstring convention.
    severity: info
    match: |
      function .* {
        if (is_exported and !has_docstring) {
          raise "Exported functions should have a comment explaining their purpose."
        }
      }

# Configure file paths to include/exclude
include:
  - src/**/*.go
  - pkg/**/*.go

exclude:
  - vendor/**/*.go
  - testdata/**/*.go

# Configure CodeRabbit’s behavior on pull requests
pull_request_review:
  title: "Code Review"
  body: "Automated review by CodeRabbit."
  approve: true

# Set up notifications for issues found
notifications:
  email: true
  slack: false

# Performance thresholds
performance:
  max_line_complexity: 15
  max_function_complexity: 10
  max_file_size_kb: 100

# Limit review to files modified in the PR
pr_scope: true

# Specific reviewer guidelines
review_guidelines:
  - Follow idiomatic Go practices
  - Minimize error-prone code and complex logic
  - Ensure test coverage for all new code